# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  # meta
  s.name        = 'bio-nexml'
  s.version     = '1.1.0'
  s.authors     = ['Rutger Vos', 'Anurag Priyam']
  s.email       = ['rutgeraldo@gmail.com', 'anurag08priyam@gmail.com']
  s.homepage    = 'https://github.com/nexml/bio-nexml'
  s.license     = 'MIT'

  s.summary     = %q{BioRuby plugin for reading and writing NeXML (http://nexml.org)}
  s.description = %q{This plugin reads, writes and generates NeXML}

  # dependencies
  s.add_dependency('bio', '>= 1.4.1')
  s.add_dependency('libxml-ruby', '= 3.0.0')

  s.add_development_dependency('test-unit', '~> 3.2.3')

  # gem
  s.files         = `git ls-files`.split("\n") rescue ''
  s.test_file     = "test/test_bio-nexml.rb"
  s.require_paths = ["lib"]
end

